### ISSUE TITLE
Struggling to run transIndel_build_RNA.py 

### ISSUE THREAD

**Issue by yesitsjess** [cauyrd/transIndel#5]
Hello, 

I'm getting an error when try to run transIndel_build_RNA.py like this:
`python transIndel/transIndel_build_RNA.py -i sam.sorted.bam -r hg38.fa -g Homo_sapiens.GRCh38.94.gtf -o sam.indels.bam`

I'm using samtools_v1.4.1. The output I get is:
```
[bam_sort_core] merging from 10 files...
Traceback (most recent call last):
  File "transIndel/transIndel_build_RNA.py", line 304, in <module>
    main()
  File "transIndel/transIndel_build_RNA.py", line 296, in main
    softclipping_realignment(mapq_cutoff, max_del_len, input, output, ref_genome, gtf, splice_bin)
  File "transIndel/transIndel_build_RNA.py", line 206, in softclipping_realignment
    subprocess.check_call("samtools index {}".format(output), shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'samtools index sam.indel.bam' returned non-zero exit sta
```

**Comment by cauyrd** [comment]
Could you send a test file so that we can check your problem, we have
tested transindel in our end and have not found any problem.
